### ISSUE TITLE
Load Diffusors node cant "see" into subfolders.

### ISSUE THREAD

**Issue by kattamaran** [GiusTex/ComfyUI-DiffusersImageOutpaint#23]
Clicking the dropdowns to choose the model or controlnet will show me only my subfolder names.

**Comment by GiusTex** [comment]
That's [intended](https://github.com/GiusTex/ComfyUI-DiffusersImageOutpaint#installation), since the folders contain config files, and the script needs to load all of them (diffusers needs to load all of them), so you have two options: include the config files elsewhere and load them separately, or include them in 1 folder, which is what I'm doing.

<details>
<summary>Details</summary>

I could implement option 1 and I was already doing it, but it was when I was trying to load diffusers models with Comfyui, and in the end I couldn't do it so I dropped the project and the part that loaded config files separately. I could add that part, but there was another problem: it required around 1 gb of vram more, to load config files separately; maybe there is some line of code somewhere to fix or online to find to fix it, but... I dunno if it's worth the trouble.

</details>

**Comment by GiusTex** [comment]
Write here if you have other problems, ideas or things to suggest or ask; I think you can open again the issue, or I'll do it if you can't
